### PR TITLE
Improve option parsing (switch to argparse)

### PR DESCRIPTION
**Pull request by mistydemeo**
This pull request improves the argument parsing by switching from getopt to argparse. argparse's ArgumentParser comes with automatic help text building, checking for mandatory options, and defaults, so it helps simplify the option generation and checking.

PS - thanks for twee2sam! It's a really neat project. :D

### CODE REVIEW

**Comment by haroldo-ok** [comment]
Okay, merged. Thanks for your contribution, and sorry for the delay! ;)

**Comment by mistydemeo** [comment]
Thanks! I'll rebase the other branches - is there an order you prefer?

**Comment by haroldo-ok** [comment]
That won't be necessary; I already merged everything. :P

**Comment by mistydemeo** [comment]
:sparkles:

**Pull request merged**
